#index
#   path: /
#   controller: App\ControllerDefaultController::index
acceuil:
    path: /
    controller: App\Controller\AccueilController::index
    
voyages:
    path: /voyages
    controller: App\Controller\VoyagesController::index
    